In [159]:
import os
cwd = os.getcwd()
print("Current Working Directory:", cwd)

pd.set_option('display.float_format', '{:.10f}'.format)

Current Working Directory: C:\Users\thoma\PycharmProjects\IntroMachineLearning\Project1

In [52]:
import numpy as np
from ucimlrepo import fetch_ucirepo
import pandas as pd
import os

def dataSourcing(dataName):
    """

    @param dataName:
    @return:
    """

    featurePath = dataName + "/featureData.csv"
    targetPath = dataName + "/targetData.csv"

    if dataName == 'BreastCancer':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + " data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + "data does not exist, reading from source")

            # fetch dataset
            breast_cancer_wisconsin_original = fetch_ucirepo(id=15)

            # data (as pandas dataframes)
            dataFeatures = pd.DataFrame(breast_cancer_wisconsin_original.data.features)
            dataTargets = pd.DataFrame(breast_cancer_wisconsin_original.data.targets)

            # write to local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # remove NAs
        dataFeatures = dataFeatures.dropna()

        # assign types to all columns
        dataFeatures.loc[:, 'Clump_thickness'] = dataFeatures['Clump_thickness'].astype(float)
        dataFeatures.loc[:, 'Uniformity_of_cell_size'] = dataFeatures['Uniformity_of_cell_size'].astype(float)
        dataFeatures.loc[:, 'Uniformity_of_cell_shape'] = dataFeatures['Uniformity_of_cell_shape'].astype(float)
        dataFeatures.loc[:, 'Marginal_adhesion'] = dataFeatures['Marginal_adhesion'].astype(float)
        dataFeatures.loc[:, 'Single_epithelial_cell_size'] = dataFeatures['Single_epithelial_cell_size'].astype(float)
        dataFeatures.loc[:, 'Bare_nuclei'] = dataFeatures['Bare_nuclei'].astype(float)
        dataFeatures.loc[:, 'Bland_chromatin'] = dataFeatures['Bland_chromatin'].astype(float)
        dataFeatures.loc[:, 'Normal_nucleoli'] = dataFeatures['Normal_nucleoli'].astype(float)
        dataFeatures.loc[:, 'Mitoses'] = dataFeatures['Mitoses'].astype(float)

        # set the name of the target column
        dataTargets = dataTargets.loc[dataFeatures.index.tolist()]
        dataTargets.columns = ['Class']

    elif dataName == 'CarEval':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + " data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + " data does not exist, reading from source")

            # fetch dataset
            car_evaluation = fetch_ucirepo(id=19)

            # store relevant data (as pandas dataframes)
            dataFeatures = pd.DataFrame(car_evaluation.data.features)
            dataTargets = pd.DataFrame(car_evaluation.data.targets)

            # write to the local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # assign types to all columns
        dataFeatures = pd.get_dummies(dataFeatures).astype(bool)

        # set the name of the target column
        dataTargets.columns = ['Class']

    elif dataName == 'CongressVoting':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + " data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + " data does not exist, reading from source")

            # fetch dataset
            congressional_voting_records = fetch_ucirepo(id=105)

            # store relevant data (as pandas dataframes)
            dataFeatures = pd.DataFrame(congressional_voting_records.data.features)
            dataTargets = pd.DataFrame(congressional_voting_records.data.targets)

            # write to the local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # reset the data to be integers. helps to account for abstain votes which will be 0's
        dataFeatures = dataFeatures.replace({'y': 1, 'n': -1})
        dataFeatures = dataFeatures.fillna(0)

        # assign types to all columns
        dataFeatures.loc[:, 'handicapped-infants'] = dataFeatures['handicapped-infants'].astype(int)
        dataFeatures.loc[:, 'water-project-cost-sharing'] = dataFeatures['water-project-cost-sharing'].astype(int)
        dataFeatures.loc[:, 'adoption-of-the-budget-resolution'] = dataFeatures[
            'adoption-of-the-budget-resolution'].astype(int)
        dataFeatures.loc[:, 'physician-fee-freeze'] = dataFeatures['physician-fee-freeze'].astype(int)
        dataFeatures.loc[:, 'el-salvador-aid'] = dataFeatures['el-salvador-aid'].astype(int)
        dataFeatures.loc[:, 'religious-groups-in-schools'] = dataFeatures['religious-groups-in-schools'].astype(int)
        dataFeatures.loc[:, 'anti-satellite-test-ban'] = dataFeatures['anti-satellite-test-ban'].astype(int)
        dataFeatures.loc[:, 'aid-to-nicaraguan-contras'] = dataFeatures['aid-to-nicaraguan-contras'].astype(int)
        dataFeatures.loc[:, 'mx-missile'] = dataFeatures['mx-missile'].astype(int)
        dataFeatures.loc[:, 'immigration'] = dataFeatures['immigration'].astype(int)
        dataFeatures.loc[:, 'synfuels-corporation-cutback'] = dataFeatures['synfuels-corporation-cutback'].astype(int)
        dataFeatures.loc[:, 'education-spending'] = dataFeatures['education-spending'].astype(int)
        dataFeatures.loc[:, 'superfund-right-to-sue'] = dataFeatures['superfund-right-to-sue'].astype(int)
        dataFeatures.loc[:, 'crime'] = dataFeatures['crime'].astype(int)
        dataFeatures.loc[:, 'duty-free-exports'] = dataFeatures['duty-free-exports'].astype(int)
        dataFeatures.loc[:, 'export-administration-act-south-africa'] = dataFeatures[
            'export-administration-act-south-africa'].astype(int)

        # set the name of the target column
        dataTargets = dataTargets.loc[dataFeatures.index.tolist()]
        dataTargets.columns = ['Class']

    elif dataName == 'Abalone':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + " data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + " data does not exist, reading from source")

            # fetch dataset
            abalone = fetch_ucirepo(id=1)

            # store relevant data (as pandas dataframes)
            dataFeatures = pd.DataFrame(abalone.data.features)
            dataTargets = pd.DataFrame(abalone.data.targets)

            # write to the local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # assign types to all columns
        # performing one hot encoding for the sex column and then dropping the original column
        dataFeatures_Sex = dataFeatures['Sex']
        dataFeatures_Sex = pd.get_dummies(dataFeatures_Sex).astype(bool)
        dataFeatures = dataFeatures.join(dataFeatures_Sex)
        dataFeatures = dataFeatures.drop(columns='Sex')

        # normalize the rest
        dataFeatures.loc[:, 'Length'] = dataFeatures['Length'].astype(float)
        dataFeatures.loc[:, 'Diameter'] = dataFeatures['Diameter'].astype(float)
        dataFeatures.loc[:, 'Height'] = dataFeatures['Height'].astype(float)
        dataFeatures.loc[:, 'Whole_weight'] = dataFeatures['Whole_weight'].astype(float)
        dataFeatures.loc[:, 'Shucked_weight'] = dataFeatures['Shucked_weight'].astype(float)
        dataFeatures.loc[:, 'Viscera_weight'] = dataFeatures['Viscera_weight'].astype(float)
        dataFeatures.loc[:, 'Shell_weight'] = dataFeatures['Shell_weight'].astype(float)

        # set the name of the target column
        dataTargets = dataTargets.loc[dataFeatures.index.tolist()]
        dataTargets.columns = ['Class']

    elif dataName == 'ComputerHardware':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + "data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + "data does not exist, reading from source")

            # fetch dataset
            computer_hardware = fetch_ucirepo(id=29)

            # data (as pandas dataframes)
            dataFeatures = pd.DataFrame(computer_hardware.data.features)
            dataTargets = pd.DataFrame(dataFeatures['PRP'])

            # write to the local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # drop the columns that we do not need
        dataFeatures = dataFeatures.drop(columns=['VendorName', 'ModelName', 'PRP', 'ERP'])

        # assign types to all columns, normalizing these
        dataFeatures.loc[:, 'MYCT'] = dataFeatures['MYCT'].astype(float)
        dataFeatures.loc[:, 'MMIN'] = dataFeatures['MMIN'].astype(float)
        dataFeatures.loc[:, 'MMAX'] = dataFeatures['MMAX'].astype(float)
        dataFeatures.loc[:, 'CACH'] = dataFeatures['CACH'].astype(float)
        dataFeatures.loc[:, 'CHMIN'] = dataFeatures['CHMIN'].astype(float)
        dataFeatures.loc[:, 'CHMAX'] = dataFeatures['CHMAX'].astype(float)

        # set the name of the target column
        dataTargets = dataTargets.loc[dataFeatures.index.tolist()]
        dataTargets.columns = ['Class']

    elif dataName == 'ForestFires':
        # check if file path exists, read from file if so, otherwise grab from online repo
        if os.path.exists(featurePath) & os.path.exists(targetPath):
            print(dataName + "data exists, reading from csv")

            # read from local directory
            dataFeatures = pd.read_csv(featurePath, index_col=0)
            dataTargets = pd.read_csv(targetPath, index_col=0)

        else:
            print(dataName + "data does not exist, reading from source")

            # fetch dataset
            forest_fires = fetch_ucirepo(id=162)

            # data (as pandas dataframes)
            dataFeatures = pd.DataFrame(forest_fires.data.features)
            dataTargets = pd.DataFrame(forest_fires.data.targets)

            # write to the local directory
            dataFeatures.to_csv(featurePath, index=True)
            dataTargets.to_csv(targetPath, index=True)

        # assign types to all columns
        # setting these to integers as they are ordinal values
        dataFeatures.loc[:, 'X'] = dataFeatures['X'].astype(int)
        dataFeatures.loc[:, 'Y'] = dataFeatures['Y'].astype(int)

        # adjust these date values to relative integer values
        month_dict = {
            'jan': 1,
            'feb': 2,
            'mar': 3,
            'apr': 4,
            'may': 5,
            'jun': 6,
            'jul': 7,
            'aug': 8,
            'sep': 9,
            'oct': 10,
            'nov': 11,
            'dec': 12
        }
        # Replace month names with integer values
        dataFeatures.loc[:, 'month'] = dataFeatures['month'].replace(month_dict)
        dataFeatures.loc[:, 'month'] = dataFeatures['X'].astype(int)

        day_dict = {
            'mon': 1,
            'tue': 2,
            'wed': 3,
            'thu': 4,
            'fri': 5,
            'sat': 6,
            'sun': 7
        }
        # Replace month names with integer values
        dataFeatures.loc[:, 'day'] = dataFeatures['day'].replace(day_dict)
        dataFeatures.loc[:, 'day'] = dataFeatures['day'].astype(int)

        # normalize these
        dataFeatures.loc[:, 'FFMC'] = dataFeatures['FFMC'].astype(float)
        dataFeatures.loc[:, 'DMC'] = dataFeatures['DMC'].astype(float)
        dataFeatures.loc[:, 'DC'] = dataFeatures['DC'].astype(float)
        dataFeatures.loc[:, 'ISI'] = dataFeatures['ISI'].astype(float)
        dataFeatures.loc[:, 'temp'] = dataFeatures['temp'].astype(float)
        dataFeatures.loc[:, 'RH'] = dataFeatures['RH'].astype(float)
        dataFeatures.loc[:, 'wind'] = dataFeatures['wind'].astype(float)
        dataFeatures.loc[:, 'rain'] = dataFeatures['rain'].astype(float)

        # set the name of the target column
        dataTargets = dataTargets.loc[dataFeatures.index.tolist()]
        dataTargets.columns = ['Class']
        dataTargets.loc[:, 'Class'] = np.log1p(dataTargets['Class'])

    return dataFeatures, dataTargets

In [172]:
currentDataSet = 'ForestFires'
features, targets = dataSourcing(currentDataSet)

print(features.info())

ForestFiresdata exists, reading from csv
<class 'pandas.core.frame.DataFrame'>
Int64Index: 517 entries, 0 to 516
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int32
 1   Y       517 non-null    int32
 2   month   517 non-null    int32
 3   day     517 non-null    int32
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    float64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
dtypes: float64(8), int32(4)
memory usage: 44.4 KB
None

In [173]:
# check summary of the targets
featuresSummary = features.describe(percentiles=[.05, .1, .15, .2, .25,
                                                 .30, .35, .40, .45, .5,
                                                 .55, .60, .65, .70, .75,
                                                 .8, .85, .9, .95, 1])
targetsSummary = targets.describe(percentiles=[.1, .3, .5, .7, .9])

#print(featuresSummary)
#isplay(targetsSummary)

print(targetsSummary.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

tuningFilePath = currentDataSet + '/KEEPTestCases/ParameterTuningFile.csv'
crossValFilePath = currentDataSet + '/KEEPTestCases/CrossValidationTestFile.csv'

parameterTuningOutput = pd.read_csv(tuningFilePath, index_col=0)
parameterTuningOutput = parameterTuningOutput.sort_values(by = ['AveragePerformance'], ascending = True)

print(parameterTuningOutput.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

#versus NULL model
crossValidationOutput = pd.read_csv(crossValFilePath, index_col=0)
crossValidationOutput['TestEstimateDiff'] = abs(crossValidationOutput['actualValue'] - crossValidationOutput['expectedValue'])
crossValidationOutput['NullEstimate'] = crossValidationOutput['actualValue'].mean()
crossValidationOutput['NullEstimateDiff'] = abs(crossValidationOutput['actualValue'] - crossValidationOutput['NullEstimate'])
crossValidationOutput['SE'] = (crossValidationOutput['TestEstimateDiff'])**2
crossValidationOutput['SE NULL'] = (crossValidationOutput['NullEstimateDiff'])**2
display(crossValidationOutput.sample(n = 10))

crossValidationOutputView = crossValidationOutput.drop(columns = ["testID", "actualValue", "expectedValue", "NullEstimate"])
display(crossValidationOutputView.describe())

print(crossValidationOutputView.describe().to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

nullModelOutput = pd.DataFrame({"TestOutput": [crossValidationOutput['SE'].mean()], 
                                "NULLModelOutput": [crossValidationOutput['SE NULL'].mean()]
                               })
print("NULL Comp")
display(nullModelOutput)

print(nullModelOutput.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

\begin{tabular}{lr}
\toprule
{} &   Class \\
\midrule
count & 517.000 \\
mean  &   1.111 \\
std   &   1.398 \\
min   &   0.000 \\
10\%   &   0.000 \\
30\%   &   0.000 \\
50\%   &   0.419 \\
70\%   &   1.729 \\
90\%   &   3.268 \\
max   &   6.996 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrrrr}
\toprule
{} &  p &   k &     e &  s &  AveragePerformance &  TestsRun \\
\midrule
19 &  1 &  16 & 0.500 &  2 &               2.581 &        10 \\
21 &  1 &  16 & 1.000 &  2 &               2.615 &        10 \\
9  &  1 &   8 & 1.000 &  2 &               2.681 &        10 \\
12 &  1 &  12 & 0.500 &  1 &               2.690 &        10 \\
37 &  2 &  12 & 0.500 &  2 &               2.691 &        10 \\
33 &  2 &   8 & 1.000 &  2 &               2.695 &        10 \\
41 &  2 &  12 & 2.000 &  2 &               2.702 &        10 \\
24 &  2 &   4 & 0.500 &  1 &               2.771 &        10 \\
35 &  2 &   8 & 2.000 &  2 &               2.848 &        10 \\
32 &  2 &   8 & 1.000 &  1 &               2.890 &        10 \\
\bottomrule
\end{tabular}

C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\4033481556.py:11: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(targetsSummary.to_latex(index=True,
C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\4033481556.py:21: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(parameterTuningOutput.to_latex(index=True,

,testID,nearestNeighbors,expectedValue,actualValue,correctAssignment,TestEstimateDiff,NullEstimate,NullEstimateDiff,SE,SE NULL
98,2,"[261, 101, 386, 198, 371, 385, 125, 451, 225, ...",1.0932421020,0.0000000000,False,1.0932421020,1.0910518801,1.0910518801,1.1951782936,1.1903942050
425,2,"[87, 505, 507, 62, 237, 262, 438, 398, 85, 457...",1.3463623504,0.0000000000,False,1.3463623504,1.0910518801,1.0910518801,1.8126915785,1.1903942050
123,2,"[113, 112, 307, 315, 39, 283, 340, 429, 314, 3...",0.9868542929,0.0000000000,False,0.9868542929,1.0910518801,1.0910518801,0.9738813954,1.1903942050
457,2,"[187, 385, 157, 515, 185, 371, 508, 305, 141, ...",1.3383998848,4.4278361707,False,3.0894362859,1.0910518801,3.3367842906,9.5446165649,11.1341294022
69,1,"[214, 72, 89, 110, 303, 210, 190, 108, 204, 35...",1.0560742176,0.0000000000,False,1.0560742176,1.0910518801,1.0910518801,1.1152927531,1.1903942050
160,4,"[1, 183, 296, 89, 301, 224, 23, 468, 172, 253,...",1.1923151175,1.0116009117,True,0.1807142058,1.0910518801,0.0794509684,0.0326576242,0.0063124564
328,1,"[368, 13, 375, 364, 311, 9, 365, 32, 446, 337,...",1.2454491632,0.0000000000,False,1.2454491632,1.0910518801,1.0910518801,1.5511436180,1.1903942050
270,3,"[267, 157, 192, 148, 345, 268, 66, 237, 425, 6...",1.1129988341,0.4187103349,False,0.6942884993,1.0910518801,0.6723415452,0.4820365202,0.4520431534
400,3,"[412, 480, 184, 483, 167, 420, 294, 171, 256, ...",1.1910949303,2.2148461787,False,1.0237512484,1.0910518801,1.1237942986,1.0480666186,1.2629136256
31,5,"[90, 306, 375, 370, 213, 342, 472, 301, 368, 4...",1.0239103362,0.0000000000,False,1.0239103362,1.0910518801,1.0910518801,1.0483923766,1.1903942050

       TestEstimateDiff  NullEstimateDiff              SE         SE NULL
count   2070.0000000000   2070.0000000000 2070.0000000000 2070.0000000000
mean       1.1578808283      1.1225125482    1.8920774502    1.8018010189
std        0.7427354429      0.7362258128    2.5681619491    2.7605380512
min        0.0006625029      0.0092467097    0.0000004389    0.0000855016
25%        0.6671753783      0.8302727935    0.4451241992    0.6893529116
50%        1.0910761083      1.0910518801    1.1904474260    1.1903942050
75%        1.4737534477      1.0910518801    2.1719492304    1.1903942050
max        4.5759243118      4.5420577413   20.9390833073   20.6302885252

\begin{tabular}{lrrrr}
\toprule
{} &  TestEstimateDiff &  NullEstimateDiff &       SE &  SE NULL \\
\midrule
count &          2070.000 &          2070.000 & 2070.000 & 2070.000 \\
mean  &             1.158 &             1.123 &    1.892 &    1.802 \\
std   &             0.743 &             0.736 &    2.568 &    2.761 \\
min   &             0.001 &             0.009 &    0.000 &    0.000 \\
25\%   &             0.667 &             0.830 &    0.445 &    0.689 \\
50\%   &             1.091 &             1.091 &    1.190 &    1.190 \\
75\%   &             1.474 &             1.091 &    2.172 &    1.190 \\
max   &             4.576 &             4.542 &   20.939 &   20.630 \\
\bottomrule
\end{tabular}

NULL Comp

C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\4033481556.py:37: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(crossValidationOutputView.describe().to_latex(index=True,

    TestOutput  NULLModelOutput
0 1.8920774502     1.8018010189

\begin{tabular}{lrr}
\toprule
{} &  TestOutput &  NULLModelOutput \\
\midrule
0 &       1.892 &            1.802 \\
\bottomrule
\end{tabular}

C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\4033481556.py:47: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(nullModelOutput.to_latex(index=True,

In [144]:
# meant for classification tests
# check summary of the targets
targetsSummary = targets.value_counts()
display(targetsSummary)

tuningFilePath = currentDataSet + '/KEEPTestCases/ParameterTuningFile.csv'
crossValFilePath = currentDataSet + '/KEEPTestCases/CrossValidationTestFile.csv'

parameterTuningOutput = pd.read_csv(tuningFilePath, index_col=0)
parameterTuningOutput = parameterTuningOutput.sort_values(by = ['AveragePerformance'], ascending = False)

crossValidationOutput = pd.read_csv(crossValFilePath, index_col=0)

display(parameterTuningOutput)
display(crossValidationOutput)

#overall performance
print(crossValidationOutput['correctAssignment'].mean())

# #see average inputs per value
# averageInputsPerInput = features.join(targets)
# averageInputsPerInput = pd.DataFrame(averageInputsPerInput.groupby('Class')[features.columns].mean())

# display(averageInputsPerInput[averageInputsPerInput.columns[0:4]])
# display(averageInputsPerInput[averageInputsPerInput.columns[4:8]])
# display(averageInputsPerInput[averageInputsPerInput.columns[8:12]])
# display(averageInputsPerInput[averageInputsPerInput.columns[12:15]])
# display(averageInputsPerInput[averageInputsPerInput.columns[15:18]])
# display(averageInputsPerInput[averageInputsPerInput.columns[[19, 20, 18]]])

# print(averageInputsPerInput[averageInputsPerInput.columns[8:12]].to_latex(index=True,
#                   formatters={"name": str.upper},
#                   float_format="{:.3f}".format,))

# print(averageInputsPerInput[averageInputsPerInput.columns[[19, 20, 18]]].to_latex(index=True,
#                   formatters={"name": str.upper},
#                   float_format="{:.3f}".format,))

#group performance by class
performanceByClassSuccess = pd.DataFrame(crossValidationOutput.groupby('actualValue')['correctAssignment'].mean())
performanceByClassSuccess.columns = ['% correct']
performanceByClassSuccess.loc[:,'% correct'] = performanceByClassSuccess['% correct'] * 100
performanceByClassCount = pd.DataFrame(crossValidationOutput.groupby('actualValue')['correctAssignment'].count())
performanceByClassCount.columns = ['totalCases']
performanceByClassSuccess = performanceByClassSuccess.join(performanceByClassCount)
#performanceByClassSuccess['expectedValueNull'] = performanceByClassSuccess['Class'].value_counts().idxmax()
print("PerformanceByClass")
display(performanceByClassSuccess)

print(crossValidationOutput['correctAssignment'].mean())

#versus NULL model
nullComp = crossValidationOutput.copy()
nullComp['expectedValueNULL'] = nullComp['actualValue'].value_counts().idxmax()
nullComp['correctAssignmentNULL'] = nullComp['actualValue'] == nullComp['expectedValueNULL']
nullModelOutput = pd.DataFrame({"TestOutput": [crossValidationOutput['correctAssignment'].mean() * 100], 
                                "NULLModelOutput": [nullModel['correctAssignment'].mean() * 100]
                               })
print("NULL Comp")
display(nullModelOutput)

print("The average accuracy of the null model is: " + str(nullModel['correctAssignment'].mean()))


print(targetsSummary.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

print(parameterTuningOutput.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

print(performanceByClassSuccess.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

print(nullModelOutput.to_latex(index=True,
                  formatters={"name": str.upper},
                  float_format="{:.3f}".format,))

Class
32       7
50       6
40       6
22       6
36       5
        ..
77       1
7        1
74       1
69       1
1150     1
Length: 116, dtype: int64

    p   k   e  s  AveragePerformance  TestsRun
34  2  10  15  1        13657.382219        10
14  1  10  10  1        13424.202868        10
30  2  10   5  1        13357.415056        10
31  2  10   5  2        13274.677685        10
27  2   7  10  2        12693.981447        10
26  2   7  10  1        12660.300564        10
25  2   7   5  2        12591.041173        10
24  2   7   5  1        12492.381131        10
33  2  10  10  2        12215.136138        10
9   1   7  10  2        11607.723311        10
7   1   7   5  2        11563.212899        10
21  2   5  10  2        11302.198861        10
19  2   5   5  2        11258.027619        10
11  1   7  15  2        11193.811702        10
10  1   7  15  1        11188.086672        10
8   1   7  10  1        10985.878991        10
6   1   7   5  1        10892.276572        10
4   1   5  15  1        10145.173413        10
1   1   5   5  2         9918.755955        10
0   1   5   5  1         9760.836055        10

,testID,nearestNeighbors,expectedValue,actualValue,correctAssignment
195,1,"[1, 5, 34, 151, 166]",217.149004,208,False
120,1,"[121, 187, 135, 188, 164]",84.162501,100,False
131,1,"[204, 142, 161, 159, 126]",35.593313,16,False
183,1,"[85, 86, 125, 139, 113]",34.000465,22,False
91,1,"[64, 1, 71, 116, 52]",136.144866,189,False
...,...,...,...,...,...
196,6,"[197, 169, 90, 19, 5]",235.319591,307,False
199,6,"[5, 191, 151, 169, 19]",234.928458,1150,False
202,6,"[203, 176, 182, 29, 37]",23.600771,18,False
204,6,"[161, 142, 45, 114, 176]",45.203393,42,True
206,6,"[161, 45, 142, 86, 114]",47.199515,52,True

0.20876494023904382
PerformanceByClass

             % correct  totalCases
actualValue
6             0.000000           8
7             0.000000           9
8             0.000000           7
10            0.000000           7
11            0.000000           7
...                ...         ...
465          13.333333          15
510           0.000000           5
636           0.000000           7
1144          0.000000           7
1150          0.000000           9

[102 rows x 2 columns]

0.20876494023904382
NULL Comp

   TestOutput  NULLModelOutput
0   20.876494        70.023148

The average accuracy of the null model is: 0.7002314814814815
\begin{tabular}{lr}
\toprule
     &  0 \\
Class &    \\
\midrule
32   &  7 \\
50   &  6 \\
40   &  6 \\
22   &  6 \\
36   &  5 \\
45   &  5 \\
24   &  5 \\
16   &  5 \\
20   &  4 \\
30   &  4 \\
26   &  4 \\
60   &  4 \\
38   &  4 \\
18   &  4 \\
12   &  4 \\
66   &  4 \\
62   &  3 \\
27   &  3 \\
33   &  3 \\
11   &  3 \\
52   &  2 \\
132  &  2 \\
208  &  2 \\
46   &  2 \\
214  &  2 \\
76   &  2 \\
70   &  2 \\
100  &  2 \\
42   &  2 \\
144  &  2 \\
277  &  2 \\
6    &  2 \\
71   &  2 \\
35   &  2 \\
34   &  2 \\
29   &  2 \\
465  &  2 \\
25   &  2 \\
138  &  2 \\
14   &  2 \\
72   &  2 \\
21   &  2 \\
17   &  2 \\
510  &  2 \\
198  &  1 \\
134  &  1 \\
136  &  1 \\
212  &  1 \\
143  &  1 \\
189  &  1 \\
140  &  1 \\
185  &  1 \\
173  &  1 \\
172  &  1 \\
141  &  1 \\
188  &  1 \\
367  &  1 \\
220  &  1 \\
237  &  1 \\
1144 &  1 \\
915  &  1 \\
636  &  1 \\
489  &  1 \\
405  &  1 \\
397  &  1 \\
370  &  1 \\
368  &  1 \\
326  &  1 \\
318  &  1 \\
307  &  1 \\
274  &  1 \\
269  &  1 \\
259  &  1 \\
248  &  1 \\
133  &  1 \\
75   &  1 \\
130  &  1 \\
120  &  1 \\
61   &  1 \\
58   &  1 \\
56   &  1 \\
54   &  1 \\
53   &  1 \\
51   &  1 \\
49   &  1 \\
44   &  1 \\
41   &  1 \\
37   &  1 \\
31   &  1 \\
28   &  1 \\
23   &  1 \\
19   &  1 \\
13   &  1 \\
10   &  1 \\
8    &  1 \\
63   &  1 \\
64   &  1 \\
65   &  1 \\
93   &  1 \\
116  &  1 \\
114  &  1 \\
113  &  1 \\
111  &  1 \\
109  &  1 \\
106  &  1 \\
105  &  1 \\
92   &  1 \\
67   &  1 \\
86   &  1 \\
84   &  1 \\
80   &  1 \\
77   &  1 \\
7    &  1 \\
74   &  1 \\
69   &  1 \\
1150 &  1 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrrrr}
\toprule
{} &  p &   k &   e &  s &  AveragePerformance &  TestsRun \\
\midrule
34 &  2 &  10 &  15 &  1 &           13657.382 &        10 \\
14 &  1 &  10 &  10 &  1 &           13424.203 &        10 \\
30 &  2 &  10 &   5 &  1 &           13357.415 &        10 \\
31 &  2 &  10 &   5 &  2 &           13274.678 &        10 \\
27 &  2 &   7 &  10 &  2 &           12693.981 &        10 \\
26 &  2 &   7 &  10 &  1 &           12660.301 &        10 \\
25 &  2 &   7 &   5 &  2 &           12591.041 &        10 \\
24 &  2 &   7 &   5 &  1 &           12492.381 &        10 \\
33 &  2 &  10 &  10 &  2 &           12215.136 &        10 \\
9  &  1 &   7 &  10 &  2 &           11607.723 &        10 \\
7  &  1 &   7 &   5 &  2 &           11563.213 &        10 \\
21 &  2 &   5 &  10 &  2 &           11302.199 &        10 \\
19 &  2 &   5 &   5 &  2 &           11258.028 &        10 \\
11 &  1 &   7 &  15 &  2 &           11193.812 &        10 \\
10 &  1 &   7 &  15 &  1 &           11188.087 &        10 \\
8  &  1 &   7 &  10 &  1 &           10985.879 &        10 \\
6  &  1 &   7 &   5 &  1 &           10892.277 &        10 \\
4  &  1 &   5 &  15 &  1 &           10145.173 &        10 \\
1  &  1 &   5 &   5 &  2 &            9918.756 &        10 \\
0  &  1 &   5 &   5 &  1 &            9760.836 &        10 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrr}
\toprule
{} &  \% correct &  totalCases \\
actualValue &            &             \\
\midrule
6           &      0.000 &           8 \\
7           &      0.000 &           9 \\
8           &      0.000 &           7 \\
10          &      0.000 &           7 \\
11          &      0.000 &           7 \\
12          &      4.167 &          24 \\
14          &      0.000 &           8 \\
16          &      4.348 &          23 \\
17          &     13.333 &          15 \\
18          &     13.043 &          23 \\
19          &      0.000 &           8 \\
20          &     48.485 &          33 \\
21          &     85.714 &           7 \\
22          &     13.793 &          29 \\
23          &      0.000 &           9 \\
24          &     30.435 &          23 \\
25          &     41.176 &          17 \\
26          &     48.387 &          31 \\
27          &     45.833 &          24 \\
28          &     25.000 &           8 \\
29          &     53.333 &          15 \\
30          &     56.667 &          30 \\
31          &     83.333 &           6 \\
32          &     36.667 &          30 \\
33          &     45.000 &          20 \\
34          &     53.333 &          15 \\
35          &     33.333 &          15 \\
36          &     39.130 &          23 \\
37          &      0.000 &           6 \\
38          &     10.714 &          28 \\
40          &     27.500 &          40 \\
41          &      0.000 &           8 \\
42          &     29.412 &          17 \\
44          &     37.500 &           8 \\
45          &     71.429 &          14 \\
46          &     14.286 &           7 \\
49          &     12.500 &           8 \\
50          &     35.556 &          45 \\
51          &      0.000 &           9 \\
52          &     33.333 &          15 \\
53          &     66.667 &           6 \\
54          &      0.000 &           7 \\
56          &      0.000 &           9 \\
58          &     57.143 &           7 \\
60          &     31.250 &          32 \\
61          &      0.000 &           7 \\
62          &      0.000 &          13 \\
64          &     14.286 &           7 \\
65          &      0.000 &           8 \\
66          &     16.667 &          30 \\
67          &      0.000 &           8 \\
69          &      0.000 &           5 \\
70          &     12.500 &          16 \\
71          &      0.000 &           7 \\
72          &      0.000 &          19 \\
75          &     60.000 &           5 \\
76          &      0.000 &           7 \\
77          &      0.000 &           6 \\
80          &     50.000 &           8 \\
84          &      0.000 &           8 \\
86          &     33.333 &           6 \\
92          &      0.000 &           7 \\
93          &      0.000 &           8 \\
100         &      0.000 &          16 \\
105         &      0.000 &           7 \\
106         &      0.000 &           7 \\
109         &      0.000 &           9 \\
113         &      0.000 &           6 \\
116         &     20.000 &           5 \\
120         &     33.333 &           6 \\
130         &      0.000 &           9 \\
132         &      0.000 &          14 \\
133         &      0.000 &           8 \\
136         &     25.000 &           8 \\
138         &      0.000 &          14 \\
141         &     42.857 &           7 \\
143         &      0.000 &           8 \\
144         &      0.000 &           7 \\
172         &      0.000 &          10 \\
173         &      0.000 &           7 \\
185         &      0.000 &           9 \\
188         &      0.000 &           7 \\
189         &      0.000 &           6 \\
198         &      0.000 &           7 \\
208         &      0.000 &          17 \\
212         &     25.000 &           8 \\
214         &      0.000 &           6 \\
220         &      0.000 &          10 \\
248         &     40.000 &          10 \\
269         &     33.333 &           6 \\
277         &     12.500 &          16 \\
307         &     37.500 &           8 \\
318         &      0.000 &           7 \\
326         &     25.000 &           8 \\
368         &      0.000 &           8 \\
370         &      0.000 &           8 \\
397         &      0.000 &           8 \\
465         &     13.333 &          15 \\
510         &      0.000 &           5 \\
636         &      0.000 &           7 \\
1144        &      0.000 &           7 \\
1150        &      0.000 &           9 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrr}
\toprule
{} &  TestOutput &  NULLModelOutput \\
\midrule
0 &      20.876 &           70.023 \\
\bottomrule
\end{tabular}

C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\2863356599.py:65: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(targetsSummary.to_latex(index=True,
C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\2863356599.py:69: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(parameterTuningOutput.to_latex(index=True,
C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\2863356599.py:73: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(performanceByClassSuccess.to_latex(index=True,
C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\2863356599.py:77: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(nullModelOutput.to_latex(index=True,

In [93]:
crossValFilePath = currentDataSet + '/KEEPTestCases/CrossValidationTestFile.csv'

parameterTuningOutput = pd.read_csv(crossValFilePath, index_col=0)

parameterTuningOutput2 = parameterTuningOutput[parameterTuningOutput['testID'].isin([2, 4, 6, 8, 10])]

parameterTuningOutput2.loc[:,'testID'] = (parameterTuningOutput2['testID']/2).astype(int)

display(parameterTuningOutput2)
parameterTuningOutput2 = parameterTuningOutput2.drop(parameterTuningOutput2.index.to_list())
display(parameterTuningOutput2)

#parameterTuningOutput2.to_csv(crossValFilePath, index=True)

C:\Users\thoma\AppData\Local\Temp\ipykernel_56212\3707114447.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parameterTuningOutput2.loc[:,'testID'] = (parameterTuningOutput2['testID']/2).astype(int)

,testID,nearestNeighbors,expectedValue,actualValue,correctAssignment
344,1,"[350, 128, 342, 1208, 1640, 227, 1199, 1667, 2...",unacc,unacc,True
604,1,"[550, 607, 1468, 556, 173, 499, 553, 721, 739,...",unacc,unacc,True
20,1,"[23, 128, 884, 227, 350, 9, 17, 38, 218, 342, ...",unacc,unacc,True
15,1,"[9, 17, 96, 1311, 771, 1313, 43, 124, 225, 109...",unacc,unacc,True
1433,1,"[1439, 1649, 1442, 1451, 1448, 1550, 1667, 677...",unacc,unacc,True
...,...,...,...,...,...
1685,2,"[1691, 1658, 1577, 1472, 1721, 1280, 1352, 167...",unacc,good,False
1690,2,"[394, 1691, 1636, 1285, 1714, 1672, 1255, 1473...",unacc,good,False
1696,2,"[1372, 1723, 1642, 833, 1453, 292, 1724, 1265,...",good,good,True
1712,2,"[1721, 1658, 1280, 1724, 1691, 1283, 1714, 157...",unacc,good,False
1717,2,"[1285, 1636, 1714, 1390, 394, 1691, 1723, 1672...",unacc,good,False

Empty DataFrame
Columns: [testID, nearestNeighbors, expectedValue, actualValue, correctAssignment]
Index: []